### PR TITLE
Buzz droid swarm fixes

### LINKED ISSUE #12: Several issues with buzz droid swarm
** Fly Casual Release Version**
Latest

**Describe the bug**
- Buzz droid Swarm does not triger its effect on overlap when it is launched and immediately overlaps a ship.
- If ship 'A' moves through a buzz droid swarm attached to Ship 'B', it gets attached to ship 'B'. Then at Initiative 0, when the critical Damage should be inflicted to only ship 'B', both ship 'A' and Ship 'B' suffer the critical damage, even if ship 'A' has not attached any buzz droid to it.
- If a buzz droid swarm Is attached to the front or back of a ship, if it overlaps ANY other object, the buzz droid has to attached to the other Side. If it overlaps any other Object at the front AND the Back, the buzz droid Swarm and the ship it is attached to, both suffer 1 normal damage. Thies does not happen to every object. It doesnt happen on overlap of an Obstacle, another buzz droid Swarm or bombs or mines.

**To Reproduce**
1. Play some games using a buzz droid swarm against the AI

### PR DESCRIPTION
**Pull request by Baledin**
Imported updates from Legacy. Working on initial collision as well as later collision now. Cleaned up and standardized the edited files. Closes #12

### CODE REVIEW

File: Assets/Scripts/Model/Content/SecondEdition/Remotes/BuzzDroidSwarm.cs [hunk 1]
```diff
@@ -71,16 +75,50 @@ public class BuzzDroidSwarmAbiliy : GenericAbility
...
+            collisionDetector.ReCheckCollisionsFinish();
+
+            if (overlapsShip)
+            {
+                foreach(GenericShip ship in collisionDetector.OverlappedShipsNow)
+                {
+                    if (!ship.RemotesOverlapped.Contains((GenericRemote) HostShip) && !Tools.IsFriendly(ship, HostShip))
+                    {
+                        ship.RemotesOverlapped.Add((GenericRemote)HostShip);
+                        Trigger trigger = RegisterAbilityTrigger(TriggerTypes.OnRemoteWasLaunched, delegate { AttachToShip(ship); });
```
Comment (philpursglove) [inline Assets/Scripts/Model/Content/SecondEdition/Remotes/BuzzDroidSwarm.cs:115]: Just given this a try, I had a turn where the first enemy ship hit the buzz droids and I got prompted whether I wanted them at the front or back so I put them at the back. Then the second ship hit them, so they attached themselves to that ship (but I didn't get prompted). And a third, and a fourth - I think I got prompted again on the third but I still put them at the back. When the buzz droids activated all four ships took the crit, not just the fourth one - they may all have been at range 0 of the swarm but I didn't think so. So I wonder if before we attach it to the current ship at line 114 we first need to detach it from any ship it's currently attached to? Sorry if this is a bit vague, I'll see if I can reproduce this tomorrow and record it.

**Review by philpursglove — APPROVED** [review]
Approving this on the basis that it seems like it's broadly working and I'm guessing it's better than what we currently have.

File: Assets/Scripts/Model/Content/SecondEdition/Remotes/BuzzDroidSwarm.cs (hunk 1 above)
Comment (Baledin) [reply Assets/Scripts/Model/Content/SecondEdition/Remotes/BuzzDroidSwarm.cs:115]: I think your idea is a good one, I didn't test this appropriately as I pulled it in from Legacy and it looked like they worked out the bugs already. I do think that there's a chance of multiple ships eating the damage each round so perhaps we hold off on moving this one forward until we sort it out?

**Comment by Baledin** [comment]
> Approving this on the basis that it seems like it's broadly working and I'm guessing it's better than what we currently have.
Nevermind, I agree, it's much better than it was. I'll add it now. :D
