### PR TITLE
No network error fix

### LINKED ISSUE #345: Fly Casual throws error when game loads and no internet connection exists
**Fly Casual Release Version**
v2.5.20251209.04

**Online Game Mode**
No

**Describe the bug**
Just loading the game leads to an error screen when an internet connection is not present.

**Expected behavior**
No errors.

**Platform/Device (be as specific as possible):**
 - OS: Windows
 - Version: 11 25H2

**Additional context**
WebRequestException: Cannot resolve destination host
Unity.Services.Authentication.WebRequest.SendAsync[T] () (at ./Library/PackageCache/com.unity.services.authentication@3.3.1/Runtime/Network/WebRequest.cs:45)
Unity.Services.Authentication.AuthenticationServiceInternal.HandleSignInRequestAsync (System.Func`1[TResult] signInRequest, System.Boolean enableRefresh) (at ./Library/PackageCache/com.unity.services.authentication@3.3.1/Runtime/AuthenticationServiceInternal.cs:276)
Rethrow as RequestFailedException: Network Error: Cannot resolve destination host
Unity.Services.Authentication.AuthenticationServiceInternal.HandleSignInRequestAsync (System.Func`1[TResult] signInRequest, System.Boolean enableRefresh) (at ./Library/PackageCache/com.unity.services.authentication@3.3.1/Runtime/AuthenticationServiceInternal.cs:294)
CloudServices.AuthenticateUnityServices () (at Assets/Scripts/Global/CloudServices.cs:57)
CloudServices.Awake () (at Assets/Scripts/Global/CloudServices.cs:31)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <ecf276dcb8654fa5bed2c5ea1a4ad870>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e509afeff7384f24a8f0ac30527ff01c>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <e509afeff7384f24a8f0ac30527ff01c>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e509afeff7384f24a8f0ac30527ff01c>:0)

### PR DESCRIPTION
**Pull request by Baledin**
Marked errors as hidden, these can be safely ignored as the Unity Auth and Remote Config modules will handle the failures themselves. No need to report to users.

### CODE REVIEW

File: Assets/Scripts/Global/Model/Console/Console.cs [hunk 1]
```diff
@@ -85,7 +85,7 @@ public static void Write(string text, bool isBold = false, string color = "")
 
         string logString = text;
         if (isBold) logString = "<b>" + logString + "</b>";
-        if (color != "") logString = "<color="+ color + ">" + logString + "</color>";
+        if (color != "") logString = "<color=" + color + ">" + logString + "</color>";
```
Comment (philpursglove) [inline Assets/Scripts/Global/Model/Console/Console.cs:88]: I daresay interpolation might be neater here but I suspect it'd be optimised in the compiler anyway...

**Review by philpursglove — APPROVED** [review]

File: Assets/Scripts/Global/Model/Console/Console.cs (hunk 1 above)
Comment (Baledin) [reply Assets/Scripts/Global/Model/Console/Console.cs:88]: You're not wrong. I was working on my laptop while out and didn't do my full run of the text. Probably not worth worrying about at this time.
