### PR TITLE
135 input issue

### LINKED ISSUE #135: Input issue
**Fly Casual Release Version**
Which version did the bug occur in?
Newest version as of 2/7/25
**Online Game Mode**
Yes/No
No
**Describe the bug**
When trying to clear existing text, i.e. IP Address input, Name, etc... error message comes up after second use of backspace. Freezes input and won't allow new input or continued clearing of preexisting text.
**To Reproduce**

**Expected behavior**
Text to clear and enable new text to be input into the window
**Screenshots**

Image

**Platform/Device (be as specific as possible):**
 - OS: [e.g. Windows, Mac, Android]
 - Version [e.g. Windows 10, iOS22]
Android 14 
**Additional context**

### PR DESCRIPTION
**Pull request by Baledin**
Replaced legacy Input Field with new TextMeshPro Input Field. Added BASIC IP address validation and error message for invalid IP addresses. Basic validation ensures that 4 octets are provided with each a number between 0 and 255.

Must import TextMesh Pro initial assets under Window > TextMesh Pro > Import Essentials

### CODE REVIEW

File: Assets/Scripts/MainMenu/Model/MainMenu.cs [hunk 1]
```diff
@@ -353,17 +353,38 @@ private void InitializeTitle()
...
+        if (octets.Length != 4) return false;
+
+        foreach (string oct in octets)
+        {
+            if (!int.TryParse(oct, out int octet)) return false;
+
+            if (octet > 255 || octet < 0) return false;
+        }
+
+        return true;
```
Comment (philpursglove) [inline Assets/Scripts/MainMenu/Model/MainMenu.cs]: Could you replace all this with `System.Net.IPAddress.TryParse`?

**Comment by Baledin** [comment]
Eh, I mean I guess that can work better :-P

Thanks for pointing that out. I've tested and updated the branch.

**Review by philpursglove — APPROVED** [review]
LGTM
