### PR TITLE
Dont allow grinq ability at range 0

### LINKED ISSUE #239: Grand Inquisitor can trigger his effect at range 0
**Fly Casual Release Version**
FlyCasual-v2.5.20250623.04-Windows

Grand Inquisitor's ability says "While you perform an attack at range 2-3...". but the game offers to activate it at range 0 and if selected you do get (wrongly) an additional die (2+1)

I used preditive shot as well and it could also be triggered at range 0. I do not think this is allowed. This said it could be that this only come up because of Grand Inquisitor's ability.

### PR DESCRIPTION
**Pull request by philpursglove**
I guess the Grand Inquisitor code pre-dates being able to attack at range 0. This turns off the offensive ability where the attack is less than range 2 as opposed to just exactly equal to 1. And turns off the defensive ability if the range is zero.

Closes #239

### CODE REVIEW

File: Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs [hunk 1]
```diff
@@ -86,7 +86,7 @@ private void RegisterInquisitorAttackAbility()
             if (HostShip.State.Force < 1)
                 return;
 
-            if (Combat.ShotInfo.Range == 1)
+            if (Combat.ShotInfo.Range < 2)
```
Comment (Baledin) [inline Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs]: Unlikely to be an issue but the ability text explicitly declares range 2-3 for the attack ability. I think we should check for those two values instead of just less than 2 (there are times when attacks can happen at longer ranges and we never know how XWA changes may impact this later).

File: Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs [hunk 2]
```diff
@@ -106,7 +106,7 @@ private void RegisterInquisitorDefenseAbility()
             if (HostShip.State.Force < 1)
                 return;
 
-            if (Combat.ShotInfo.Range > 1)
+            if (Combat.ShotInfo.Range != 1)
```
Comment (Baledin) [inline Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs]: This is fine as is, but it would be cleaner to add the condition as an OR to line 106.

**Review by Baledin — CHANGES_REQUESTED** [review]

File: Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs [hunk 3]
```diff
@@ -86,7 +86,7 @@ private void RegisterInquisitorAttackAbility()
             if (HostShip.State.Force < 1)
                 return;
 
-            if (Combat.ShotInfo.Range == 1)
+            if (Combat.ShotInfo.Range == 2 || Combat.ShotInfo.Range == 3)
                 return;
```
Comment (Baledin) [inline Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs:90]: I think you reversed this logic now... it's exiting the ability if Range 2 or 3 instead of only using it if Range 2 or 3.

**Review by Baledin — CHANGES_REQUESTED** [review]

File: Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs (hunk 3 above)
Comment (Baledin) [reply Assets/Scripts/Model/Content/SecondEdition/Pilots/Empire/TIEAdvancedV1/GrandInquisitor.cs:90]: If (Combat.ShotInfo.Range < 2 || Combat.ShotInfo.Range > 3) return;
This would work, perhaps you meant to change the equality symbol there.

**Review by Baledin — APPROVED** [review]
