### PR TITLE
CloudServices Update

### LINKED ISSUE #146: Crash Report: IOException: Sharing violation on path AppData\LocalLow\Baledin\Fly Casual\eventcache
**Fly Casual Release Version**
v2.5.20241101.04

Crash Report

System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode) (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode)
Unity.Services.Analytics.Internal.FileSystemCalls.OpenFileForReading (System.String path) (at <a095d6b992a947d8a7ed2db44df1d476>:0)
Unity.Services.Analytics.Internal.DiskCache.Read (System.Collections.Generic.List`1[T] eventEndIndices, System.IO.Stream buffer) (at <a095d6b992a947d8a7ed2db44df1d476>:0)
Unity.Services.Analytics.Internal.BufferX.LoadFromDisk () (at <a095d6b992a947d8a7ed2db44df1d476>:0)
Unity.Services.Analytics.AnalyticsServiceInstance.Activate () (at <a095d6b992a947d8a7ed2db44df1d476>:0)
Unity.Services.Analytics.AnalyticsServiceInstance.StartDataCollection () (at <a095d6b992a947d8a7ed2db44df1d476>:0)
CloudServices.Start () (at <19e7d3b64a8347fba27c5ba6030af584>:0)

### PR DESCRIPTION
**Pull request by Baledin**
Check current status before calling initialization or fetch calls. Closes #146.

### CODE REVIEW

File: Assets/Scripts/Global/CloudServices.cs [hunk 1]
```diff
@@ -22,14 +22,24 @@ private void Start()
 
     async void Awake()
```
Comment (philpursglove) [inline Assets/Scripts/Global/CloudServices.cs]: VS suggests this method isn't used, but I'm assuming it gets called by a Unity thing. Could it be `async Task` rather than `async void`?

**Review by philpursglove — APPROVED** [review]
LGTM

File: Assets/Scripts/Global/CloudServices.cs (hunk 1 above)
Comment (Baledin) [reply Assets/Scripts/Global/CloudServices.cs]: I would prefer async Task but it doesn't match the signature that Unity uses. I should have used Private for an access modifier but not critical that I didn't. It works fine, as you guessed, it's a Unity thing (just as Start() and Update() are).
