### PR TITLE
Version Check Updates

### LINKED ISSUE #95: Version Checking not working
**Fly Casual Release Version**
20241101.01 - likely back to 20230924.01

**Online Game Mode**
No

**Describe the bug**
Forking and updating Unity version of Fly Casual broke the Remote Settings options used for displaying developer driven messages and version checks.

**Expected behavior**
An Update Version link should appear if the version is out-of-date.

**Additional context**
Replace RemoteSettings with new Remote Config Service

### PR DESCRIPTION
**Pull request by Baledin**
Implemented Remote Config service. Closes #95

### CODE REVIEW

File: Assets/Scripts/Global/RemoteConfig.cs [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+        public string UpdateLink;
+    }
+
+    async Task InitializeRemoteConfigAsync()
+    {
+        // initialize handlers for unity game services
+        await UnityServices.InitializeAsync();
+
+        // remote config requires authentication for managing environment information
+        if (!AuthenticationService.Instance.IsSignedIn)
```
Comment (philpursglove) [inline Assets/Scripts/Global/RemoteConfig.cs:24]: I was going to say if we're signing in anonymously, do we even need to worry about whether we're already signed in, but I'm guessing if we are signed in we cut out an unnecessary network call here?

**Review by philpursglove — APPROVED** [review]
Looks fine to me. I don't know my way round the Unity side of things but I can see what it's doing and it all builds OK. :shipit:

File: Assets/Scripts/Global/RemoteConfig.cs (hunk 1 above)
Comment (Baledin) [reply Assets/Scripts/Global/RemoteConfig.cs:24]: My understanding (this piece was new to me) was that it required anonymous authentication which wasn't necessarily automatic--seems odd, but that's how it is. :D
