### PR TITLE
Tallon roll obstacle fix

### LINKED ISSUE #174: Obstacle Rules not Correct
**Fly Casual Release Version**
20241101.05

**Online Game Mode**
Yes/No

**Describe the bug**
1. If a ship start its maneuver on an Obstacle, it is suffering the effects of overlapping and moving through that obstacle. This is wrong.
2. When a ship performs a tallon Roll, it may choose to align fron/center/back on the template. If the center position overlaps an obstacle, but the front/back does not, the ship still suffers the effect of Overlapping that obstacle,  even if it is not overlapping.

**To Reproduce**
1. Do a Tallon Roll that overlaps only the center position, not front or back.
2. Game makes you suffer overlap effect, even if you chose a position that does not overlap
3. Start next turn on obstacle but fly off,  moving through the obstacle.
4. Suffer effects of obstacle

**Expected behavior**
When you start your activation on an obstacle,  you only suffer the effects of that obstacle when you finish your maneuver onlthat obstacle (when you get blocked or do a short maneuver on a long obstacle). If you clear an obstacle you started your activation on,  you dont suffer any effect from it.

**Screenshots**

**Platform/Device (be as specific as possible):**
 - OS: [e.g. Windows, Mac, Android]
 - Version [e.g. Windows 10, iOS22]

**Additional context**

### PR DESCRIPTION
**Pull request by Baledin**
Tallon Roll should now take final position into account when determining obstacles hit/landed.

Easiest way to test is to place a large obstacle exactly range 2 from your starting board edge, have an X-Wing at a 45 degree angle from this asteroid and select a Speed 3 Tallon Roll maneuver. If set up correctly, Center and Back should be at the edge of the asteroid (touching), and Forward will miss the asteroid entirely. Consequences of the choice should be as expected now.

### CODE REVIEW

**Comment by Baledin** [comment]
Just realized that this fix relies on #347 or may not work as expected as that fix resolves double counts when passing/landing on asteroids. I've rebased this on those changes so that you can check out the whole branch to test both issues.

**Comment by Baledin** [comment]
Realized I wasn't calling the Dispose method/using the TallonRollHelper to autoclose. Unfortunately, getting errors when I do so pulling this back until I can resolve it. It'll likely not be an issue except maybe a performance hit.

**Comment by Baledin** [comment]
Reverted the IDisposable implementation and moved the DestroyTemporaryShipBases call until after the program was done with them. This performs cleanup as expected now.

File: Assets/Scripts/View/ShipStandCollider/ObstaclesStayDetector.cs [hunk 1]
```diff
@@ -23,19 +23,19 @@ void OnTriggerEnter(Collider collisionInfo)
...
+            else if (collisionInfo.CompareTag("Mine"))
             {
-                if (!OverlapedMines.Contains(collisionInfo))
+                if (!OverlappedMines.Contains(collisionInfo))
                 {
-                    OverlapedMines.Add(collisionInfo);
+                    OverlappedMines.Add(collisionInfo);
                 }
             }
             else if (collisionInfo.name == "OffTheBoard")
```
Comment (philpursglove) [inline Assets/Scripts/View/ShipStandCollider/ObstaclesStayDetector.cs]: I'm never hugely keen on a set of  `else if this else if that else if something else`s, I've reworked the collisionInfo.name block into a `switch` that I think's a little neater - but feel free to disagree!

```suggestion
            switch (collisionInfo.name)
{
    case "OffTheBoard":
        OffTheBoard = true;
        break;
    case "ObstaclesStayDetector":
        if (!this.CompareTag(collisionInfo.tag))
        {
            Game.Movement.CollidedWith = collisionInfo;
            OverlapsShip = true;
            if (!OverlappedShips.Contains(Roster.GetShipById(collisionInfo.tag)))
            {
                OverlappedShips.Add(Roster.GetShipById(collisionInfo.tag));
            }
        }
        break;
    case "RemoteCollider":
        if (!this.CompareTag(collisionInfo.tag)
            && !OverlappedRemotes.Contains(Roster.GetShipById(collisionInfo.tag) as GenericRemote))
        {
            OverlappedRemotes.Add(Roster.GetShipById(collisionInfo.tag) as GenericRemote);
        }
        break;
}
```

**Review by philpursglove — APPROVED** [review]
Fixed a typo plus one suggestion but otherwise I tried it out and it seems fine to me 😄

File: Assets/Scripts/View/ShipStandCollider/ObstaclesStayDetector.cs (hunk 1 above)
Comment (Baledin) [reply Assets/Scripts/View/ShipStandCollider/ObstaclesStayDetector.cs]: This doesn't quite work as some are checking tags and some are checking names. I didn't like it either and only changed what I felt I could without impacting other code.

Comment (Baledin) [reply Assets/Scripts/View/ShipStandCollider/ObstaclesStayDetector.cs]: nvm, I see you only did it for the collisionInfo.name. That part would work.

Comment (philpursglove) [reply Assets/Scripts/View/ShipStandCollider/ObstaclesStayDetector.cs]: I started down looking at nested switches but that felt like I was trying to get too clever...

**Comment by Baledin** [comment]
@philpursglove Heads up, when making suggestions in the code, please make sure that they're complete. I had accepted it but realized it didn't delete the remaining else if statements which left a little mess to clean up. ;-)

**Comment by philpursglove** [comment]
> @philpursglove Heads up, when making suggestions in the code, please make sure that they're complete. I had accepted it but realized it didn't delete the remaining else if statements which left a little mess to clean up. ;-)

Sorry about that. It's why I don't do suggestions in PRs very often, I can never figure out the formatting to replace a whole block correctly :-(

**Comment by Baledin** [comment]
Same, honestly. I wish the interface were a little easier in this regard.
